application.rbの編集
kunihiko-yonenaga/qiita_clone pull request #12
Opened 2019-09-11 12:48 UTC by kunihiko-yonenaga

## 変更概要
+ application.rbの編集

2019-09-11 12:54 UTC, mc-chinju approved these changes

2019-09-11 12:58 UTC, mc-chinju requested changes
一回 Approve しちゃいましたが、1箇所間違いがあるので直しましょう。

2019-09-11 12:58 UTC, mc-chinju commented on config/application.rb
> +                       fixture_replacement: :factory_bot,
ここの記述間違っているので消しちゃいましょう。
正しくは以下のようになります。

```rb
g.test_framework :rspec,
                   fixtures: true,
                   view_specs: false,
                   routing_specs: false,
                   helper_specs: false,
                   controller_specs: false,
                   request_specs: false
  g.fixture_replacement :factory_bot, dir: "spec/factories"
```

参考: https://github.com/thoughtbot/factory_bot_rails

2019-09-12 01:38 UTC, mc-chinju commented on config/application.rb
> +                       fixture_replacement: :factory_bot,
上記の修正でも動作するのですが

以下の部分を  
https://github.com/kunihiko-yonenaga/qiita_clone/blob/master/Gemfile#L34-L36

`group :development, :test do` に移動させれば、単に `fixture_replacement: :factory_bot,` を書かなくても動作します。

これは、[公式ドキュメント](https://github.com/thoughtbot/factory_bot_rails) にしっかり目を通すとわかります。

2019-09-12 03:44 UTC, kunihiko-yonenaga commented on config/application.rb
> +                       fixture_replacement: :factory_bot,
公式ドキュメント目通してみました
リンクありがとうございました
変更したらPRお送りいたします

2019-09-12 05:38 UTC, mc-chinju approved these changes
LGTM です！

2019-09-12 09:21 UTC, merged