validation追加
kunihiko-yonenaga/qiita_clone pull request #16
Opened 2019-10-19 11:31 UTC by kunihiko-yonenaga

## 変更点概要
+ article,user,commentのvalidation追加

2019-10-26 09:46 UTC, mc-chinju requested changes
設定したバリデーションに対するテストはしっかりかけていていいですね！

気になるところ一通りコメントしましたのでご確認ください！


あと、rubocop 走らせてあげるといくつかエラーすると思うので、それらも直してあげましょう！

2019-10-26 09:46 UTC, mc-chinju commented on spec/models/article_spec.rb
> +    fcontext "記事が書かれていないとき" do
f は消しましょう！

2019-10-26 09:46 UTC, mc-chinju commented on app/models/user.rb
> +  validates :name, presence: true, uniqueness: true
ここはどういう仕様にするか次第なんですが、例えば同じサービス内に「サトシ」という名のユーザーを1人しか許さないか、被っても許すかのバリデーションがここになります。

この場合許さないわけですね。考えてこの仕様にしているならもちろんオッケーですが、他と合わせてこれにしただけであれば、どうするか考えてから決めましょう！

2019-10-26 09:46 UTC, mc-chinju commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
devise_auth_token で最低限のメールアドレスのバリデーションは実は設定されています。仮にそれがない場合、ここのメールアドレスに 「ラベッシ」みたいな文字列を入れても許容されてしまうわけです。

少なくとも以下の設定は必要ということは把握しておくといいかもですね。

 - xxx@yyy.zzz のような形式であること
 - 半角英数字のみで構成された文字列であること
 - 値が存在すること（これはおっけー）
 - メールアドレスの重複は許さない（これはおっけー）

他にも xxx の文字数は何文字から何文字までおっけーかな？許可しない半角英数字はあるかな？

とか結構考慮することあるんですよね。
今回は、gem 側で最低限設定されているので、この行を消すだけでひとまずおっけーです。
余裕があれば、gem 側でどんなバリデーションがされているかも調べてみましょう！

2019-10-26 09:46 UTC, mc-chinju commented on spec/models/article_spec.rb
> +      it "バリデーションがとおる" do
超細かいですが、とおる や 通る など、表記ブレがあるのでこういった部分も統一してあげるとベターです！

2019-10-27 07:12 UTC, kunihiko-yonenaga commented on app/models/user.rb
> +  validates :name, presence: true, uniqueness: true
これは完全に深く考えず入れたバリデーションでした
不便なのでuniquenessとそれに対応するテスト消しました

2019-10-27 08:04 UTC, mc-chinju approved these changes
いいですね！LGTM です！

2019-10-27 08:07 UTC, merged